---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Enable EPEL repository
      package:
        name: epel-release
        state: present

  roles:
    - role: ansible-role-gridftp
      vars:
        role_gridftp_datainterface: gridftp.grid.vbc.ac.at
        grid_host_certificate:
          cert: /srv/certificates/host.crt
          key: /srv/certificates/host.key
          remote_src: true
